prepare full travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,13 +2,24 @@ language: php
 
 matrix:
     include:
+        - php: 7.1
+          env: CODE_ANALYSIS=true
+        - php: 7.1
+          env: COMPOSER_FLAGS="--prefer-lowest"
         - php: 7.2
+          env: MONOREPO_SPLIT=true
 
 before_install:
     - phpenv config-rm xdebug.ini
 
 install:
-    - composer install
+    - composer update $COMPOSER_FLAGS
+
+before_script:
+    # make the script fail for any failed command
+    - set -e
+    # disable xdebug to fasten process
+    - phpenv config-rm xdebug.ini || return 0
 
 script:
     - vendor/bin/phpunit
@@ -16,13 +27,25 @@ script:
     # validate packages composer.json
     - vendor/bin/monorepo-builder validate
 
-    # check coding standards
-    - composer check-cs
-
-    # static analysis
-    - composer phpstan
+    # code analysis
+    - |
+      if [[ $CODE_ANALYSIS == true ]]; then
+        composer check-cs
+        composer phpstan
+      fi
 
     # this checks that the YAML config files contain no syntax errors
     - ./bin/console lint:yaml config
     # this checks that the Twig template files contain no syntax errors
     - ./bin/console lint:twig templates
+
+after_script:
+    # split monorepo to packages - only on merge to master
+    # see https://www.tomasvotruba.cz/blog/2018/07/19/how-to-make-github-and-travis-split-monorepo-to-multiple-git-repositories-for-you/
+    - |
+      if [[ $TRAVIS_EVENT_TYPE == "push" && $MONOREPO_SPLIT == true && $TRAVIS_BRANCH == "master" ]]; then
+        vendor/bin/monorepo-builder split -v
+      fi
+
+notifications:
+    email: false
